# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rnmamod-article.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(rnmamod)
library(plotly)
library(ggplot2)
library(palmerpenguins)


## ----table-one-interactive, eval = knitr::is_html_output(), layout = "l-body-outset"----
#> t1 <- data.frame(pkg = c("bnma", "gemtc", "metapack", "multinma", "netmeta", "NMADiagT", "nmaINLA",
#>                          "NMAoutlier", "nmaplateplot", "nmarank", "nmathresh", "pcnetmeta"),
#> 
#>                  bayesian = c("X", "X", "X", "X", "", "X", "X", "", "X", "X", "X", "X"),
#> 
#>                  frequentist = c("", "", "", "", "X", "", "", "X", "X", "X", "X", ""),
#> 
#>                  #exact = c("X", "X", "", "X", "", "X", "X", "", "X", "X", "X","X"),
#> 
#>                  #approx = c("", "X", "X", "", "X", "", "", "X", "X", "X", "X", ""),
#> 
#>                  contrast = c("X", "X", "X", "X", "X", "", "X", "X", "X", "X", "X", ""),
#> 
#>                  armbased = c("", "", "", "", "", "X", "", "", "", "", "", "X"),
#> 
#>                  widescope = c("X", "X", "", "X", "X", "", "X", "", "", "", "", "X"),
#> 
#>                  narrowscope = c("", "", "X", "", "", "X", "", "X", "X", "X", "X", ""),
#> 
#>                  aggregate = c("X", "X", "X", "", "X", "X", "X", "X", "X", "X", "X", "X"),
#> 
#>                  mixture = c("", "", "", "X", "", "", "", "", "", "", "", ""))
#> 
#> pkg_author <- c("https://CRAN.R-project.org/package=bnma",
#>                 "https://CRAN.R-project.org/package=gemtc",
#>                 "https://CRAN.R-project.org/package=metapack",
#>                 "https://CRAN.R-project.org/package=multinma",
#>                 "https://CRAN.R-project.org/package=netmeta",
#>                 "https://CRAN.R-project.org/package=NMADiagT",
#>                 "https://CRAN.R-project.org/package=nmaINLA",
#>                 "https://CRAN.R-project.org/package=NMAoutlier",
#>                 "https://CRAN.R-project.org/package=nmaplateplot",
#>                 "https://CRAN.R-project.org/package=nmarank",
#>                 "https://CRAN.R-project.org/package=nmathresh",
#>                 "https://CRAN.R-project.org/package=pcnetmeta")
#> t1 %>%
#>   dplyr::mutate(pkg = kableExtra::cell_spec(pkg, "html", link = pkg_author)) %>%
#>   knitr::kable(caption = "Features of R packages for network meta-analysis (CRAN Task View)",
#>                col.names = c("Package", "Bayesian", "Frequentist", #"Exact", "Normal approx.",
#>                            "Contrast", "Arm", "Wide", "Narrow", "AD", "AD & IPD"),
#>                align = "lcccccccc",
#>                format = "html",
#>                escape = FALSE,
#>                booktabs = TRUE) %>%
#>   kableExtra::row_spec(0, bold = TRUE) %>%
#>   kableExtra::kable_classic(font_size = 7) %>%
#>   kableExtra::add_header_above(c("", "Analysis" = 2, #"Input data distribution" = 2,
#>                                  "Modeling approach" = 2, "Scope breadth" = 2, "Outcome structure" = 2),
#>                                bold = TRUE) %>%
#>   #kableExtra::kable_classic(full_width = F) %>%
#>       #kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
#>       #add_indent(c(7,8)) %>%
#>   kableExtra::footnote(general = c("AD, aggregate data; IPD, individual patient data.",
#>                                    "multinma uses the probabilistic programming language Stan.",
#>                                    "nmaINLA uses integrated nested Laplace approximation.",
#>                                    "nmarank is mainly frequentist-driven but can be easily applied to Bayesian results (Papakonstantinou et al. 2022).",
#>                                    "nmathresh is mainly Bayesian-driven but can be naturally applied to the frequentist framework (Phillippo et al. 2018)."),
#>                        footnote_as_chunk = FALSE)


## ----table-one, eval = knitr::is_latex_output()-------------------------------
t1 <- data.frame(pkg = c("bnma (Seo and Schmidt 2022)", "gemtc (van Valkenhoef and Kuiper 2021)", 
                         "metapack (Lim et al. 2022)", "multinma (Phillippo 2022)", "netmeta (Rücker et al. 2022)",
                         "NMADiagT (Lu et al. 2020)", "nmaINLA (Günhan 2021)", "NMAoutlier (Petropoulou et al. 2021)", 
                         "nmaplateplot (Wang et al. 2021)", "nmarank (Nikolakopoulou et al. 2021)", 
                         "nmathresh (Phillippo et al. 2018)", "pcnetmeta (Lin et al. 2022)"),
                         
                 bayesian = c("X", "X", "X", "X", "", "X", "X", "", "X", "X", "X", "X"),
                 
                 frequentist = c("", "", "", "", "X", "", "", "X", "X", "X", "X", ""), 
                 
                 #exact = c("X", "X", "", "X", "", "X", "X", "", "X", "X", "X","X"),
                 
                 #approx = c("", "X", "X", "", "X", "", "", "X", "X", "X", "X", ""),
                 
                 contrast = c("X", "X", "X", "X", "X", "", "X", "X", "X", "X", "X", ""),
                 
                 armbased = c("", "", "", "", "", "X", "", "", "", "", "", "X"),
                 
                 widescope = c("X", "X", "", "X", "X", "", "X", "", "", "", "", "X"),
                 
                 narrowscope = c("", "", "X", "", "", "X", "", "X", "X", "X", "X", ""),
                 
                 aggregate = c("X", "X", "X", "", "X", "X", "X", "X", "X", "X", "X", "X"),
                 
                 mixture = c("", "", "", "X", "", "", "", "", "", "", "", ""))

pkg_author <- c("https://CRAN.R-project.org/package=bnma", 
                "https://CRAN.R-project.org/package=gemtc", 
                "https://CRAN.R-project.org/package=metapack", 
                "https://CRAN.R-project.org/package=multinma", 
                "https://CRAN.R-project.org/package=netmeta", 
                "https://CRAN.R-project.org/package=NMADiagT", 
                "https://CRAN.R-project.org/package=nmaINLA", 
                "https://CRAN.R-project.org/package=NMAoutlier", 
                "https://CRAN.R-project.org/package=nmaplateplot",
                "https://CRAN.R-project.org/package=nmarank", 
                "https://CRAN.R-project.org/package=nmathresh", 
                "https://CRAN.R-project.org/package=pcnetmeta")
t1 %>% 
  dplyr::mutate(pkg = kableExtra::cell_spec(pkg, "latex", link = pkg_author)) %>% 
knitr::kable(t1,
             caption = "Features of R packages for network meta-analysis (CRAN Task View)",
             col.names = c("Package", "Bayesian", "Frequentist", #"Exact", "Normal approx.",
                           "Contrast", "Arm", "Wide", "Narrow", "AD", "AD & IPD"),
             align = "lcccccccc",
             format = "latex",
             escape = TRUE,
             booktabs = TRUE) %>% 
  kableExtra::row_spec(0, bold = TRUE) %>%
  kableExtra::kable_classic(font_size = 7) %>%
  kableExtra::add_header_above(c("", "Analysis" = 2, #"Input data distribution" = 2,
                                 "Modeling approach" = 2, "Scope breadth" = 2, "Outcome structure" = 2), 
                               bold = TRUE) %>% 
  #kableExtra::kable_classic(full_width = F) %>%
      #kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE) %>%
      #add_indent(c(7,8)) %>% 
  kableExtra::footnote(general = c("AD, aggregate data; IPD, individual patient data.",
                                   "multinma uses the probabilistic programming language Stan.", 
                                   "nmaINLA uses integrated nested Laplace approximation.",
                                   "nmarank is mainly frequentist-driven but can be easily applied to Bayesian results (Papakonstantinou et al. 2022).",
                                   "nmathresh is mainly Bayesian-driven but can be naturally applied to the frequentist framework (Phillippo et al. 2018)."),
                       footnote_as_chunk = FALSE)


## ----network-models, out.width = "100%", out.height = "30%", fig.cap = "Network of functions for data preparation and model implementation", fig.alt=""----
knitr::include_graphics("network_models.png")


## ----network-visualisation, out.width = "100%", out.height = "30%", fig.cap = "Network of functions for summarising and presenting the analysis results", fig.alt=""----
knitr::include_graphics("network_visualisation.png")


## ----penguins-plotly, echo = TRUE, fig.height = 5, fig.cap="A basic interactive plot made with the plotly package on palmer penguin data. Three species of penguins are plotted with bill depth on the x-axis and bill length on the y-axis. When hovering on a point, a tooltip will show the exact value of the bill depth and length for that point, along with the species name.", include=knitr::is_html_output(), eval=knitr::is_html_output(), fig.alt = "A scatterplot of bill length against bill depth, both measured in millimetre. The three species are shown in different colours and loosely forms three clusters. Adelie has small bill length and large bill depth, Gentoo has small bill depth but large bill length, and Chinstrap has relatively large bill depth and bill length."----
#> p <- penguins %>%
#>   ggplot(aes(x = bill_depth_mm, y = bill_length_mm,
#>              color = species)) +
#>   geom_point()
#> ggplotly(p)


## ----penguins-ggplot, echo = TRUE, fig.height = 5, fig.cap="A basic non-interactive plot made with the ggplot2 package on palmer penguin data. Three species of penguins are plotted with bill depth on the x-axis and bill length on the y-axis. Visit the online article to access the interactive version made with the plotly package.", include=knitr::is_latex_output(), eval=knitr::is_latex_output()----
penguins %>% 
  ggplot(aes(x = bill_depth_mm, y = bill_length_mm, 
             color = species)) + 
  geom_point()

