# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit rnmamod-article.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
options(tinytex.verbose = TRUE)
library(rnmamod)
library(dplyr)
library(kableExtra)
library(ggplot2)


## ----network-models, out.width = "100%", out.height = "30%", fig.cap = "Network of functions for data preparation and model implementation", fig.alt=""----
knitr::include_graphics("network_models.png")


## ----network-visualisation, out.width = "100%", out.height = "30%", fig.cap = "Network of functions for summarising and presenting the analysis results", fig.alt=""----
knitr::include_graphics("network_visualisation.png")

